### ISSUE TITLE
After upgrading to 0.64.1, when tyring to login via the non-legacy iOS or Android app, I get me.emails.find is not a function error.

### ISSUE THREAD

**Issue by genesplicer** [RocketChat/Rocket.Chat#10810]
### Description:

When I upgraded to the newest release, 0.64.1 by following the upgrade steps of the tar version, everything works fine on the Desktop apps, but for the mobile apps (the non-legacy) on both Android and iOS, I am not able to login via CAS of our institution.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.64.1
* Operating System: Linux
* Deployment Method(snap/docker/tar/etc): tar (Native)
* Number of Running Instances: 1
* DB Replicaset Oplog: Enabled
* Node Version: 8.11.1
* mongoDB Version: 3.2.17
![tempfileforshare_20180518-114115](https://user-images.githubusercontent.com/18407318/40247223-5047a254-5a91-11e8-8171-ed5d522dc6a5.jpg)

### Steps to Reproduce:

1. Upgrade to v0.64.1

### Expected behavior:

Login to the Android and iOS apps normally.

### Actual behavior:

Popup on Android saying "me.emails.find is not a function".

### Relevant logs:
On the server side, these are the logs:

```[34mI20180518-11:40:46.383(-5) rocketchat_logger rocketchat_logger.js:278 [34mCAS ➔ debug Using CAS_base_url: https://cas.someuniv.edu/cas 
[34mI20180518-11:40:46.400(-5) rocketchat_logger rocketchat_logger.js:278 [34mCAS ➔ info Validated user: genesplicer 
[34mI20180518-11:40:49.601(-5) rocketchat_logger rocketchat_logger.js:278 [34mCAS ➔ debug Sourced internal attribute: email = %email% 
[34mI20180518-11:40:49.603(-5) rocketchat_logger rocketchat_logger.js:278 [34mCAS ➔ debug Sourced internal attribute: name = %firstname%, %lastname% 
[34mI20180518-11:40:49.604(-5) rocketchat_logger rocketchat_logger.js:278 [34mCAS ➔ debug Looking up user by id: genesplicer 
[34mI20180518-11:40:49.607(-5) rocketchat_logger rocketchat_logger.js:278 [34mCAS ➔ debug Using existing user for 'genesplicer' with id: BtPNda3MErKGZubrK 
[34mI20180518-11:40:49.726(-5) rocketchat_logger rocketchat_logger.js:278 [34mAPI v1 Logger ➔ debug GET: /api/v1/me 
[34mI20180518-11:40:49.727(-5) rocketchat_logger rocketchat_logger.js:278 [34mAPI v1 Logger ➔ debug get me threw an error: TypeError: me.emails.find is not a function     at Object.get (/var/www/Rocket.Chat/programs/server/packages/rocketchat_api.js:4310:37)     at Object._internalRouteActionHandler [as action] (/var/www/Rocket.Chat/programs/server/packages/rocketchat_api.js:185:39)     at Route.share.Route.Route._callEndpoint (/var/www/Rocket.Chat/programs/server/packages/nimble_restivus.js:347:32)     at /var/www/Rocket.Chat/programs/server/packages/nimble_restivus.js:236:33     at packages/simple_json-routes.js:98:9  
[34mI20180518-11:40:49.728(-5) rocketchat_logger rocketchat_logger.js:278 [34mAPI ➔ debug Failure { statusCode: 400,   body: { success: false, error: 'me.emails.find is not a function' } } ```

**Comment by graywolf336** [comment]
https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-api/server/v1/misc.js#L46
