### ISSUE TITLE
[7.7.1] The application GUI just crashed on admin login

### ISSUE THREAD

**Issue by isthevao** [RocketChat/Rocket.Chat#36304]
### Description:

I have a fresh installation that I started with version 7.6.0 and then updated to 7.7.1. When a user with the admin role logs in, they receive the error: "Application Error - The application GUI just crashed."
If I remove the admin role from the user, they can log in successfully after refreshing the page. But as soon as I reassign the admin role, the same error happens again.

I’ve checked older issues and tried the suggested fixes, but none of them solved the problem:
- The user has empty banners: banners: {}
- The user has empty settings: settings: {}
- The db.rocketchat_banner collection is empty
- The Canned_Responses_Enable setting was deleted

My users are created via OAuth. I was able to log in with an admin user before, but I'm not sure at what point it stopped working.

These tests were done in the browser. On the iOS app, the user is able to log in, but the admin panel keeps loading indefinitely.

### Steps to reproduce:

1. Assign the admin role to the user.
2. Log in with the user who has the admin role.
3. Observe the error: "Application Error - The application GUI just crashed."
4. Remove the admin role from the user.
5. Refresh the page — the user can now log in without error.
6. Reassign the admin role to the user.
7. Refresh the page again — the error returns.

### Expected behavior:

Admin user should login normally.

### Actual behavior:

The user cannot login and the message "Application Error - The application GUI just crashed." is displayed.

### Server Setup Information:

- Version of Rocket.Chat Server: 7.7.1
- License Type: Community
- Number of Users: 10
- Operating System: Docker image
- Deployment Method: Docker
- Number of Running Instances: 1
- DB Replicaset Oplog: 1 mongo instance on Docker
- NodeJS Version: 
- MongoDB Version: 6.0

### Client Setup Information

- Desktop App or Browser Version: All browsers (Edge, Chrome, Brave)
- Operating System: Windows

### Additional context

-

### Relevant logs:

There is no log output in the server application. The only log I see is from the browser console:
verifyErrors.js:34 Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at sv (verifyErrors.js:34:1)
    at d (verifyErrors.js:34:1)
    at m (verifyErrors.js:34:1)
    at M (verifyErrors.js:34:1)
    at aj (verifyErrors.js:34:1)
    at i (verifyErrors.js:34:1)
    at si (verifyErrors.js:34:1)
    at so (verifyErrors.js:34:1)
    at su (verifyErrors.js:34:1)
    at i3 (verifyErrors.js:34:1)

**Comment by Devnil434** [comment]
can i work in this issue @isthevao

**Comment by reetp** [comment]
> can i work in this issue @isthevao 
> 

You don't need to `@` people

Anyone can work on any issue, but you really need to understand the setup so you can replicate the issue.

Check https, websockets, and clearing caches are the first things to check.

Then look at debug logging, and the Oauth setup.

**Comment by bkonia** [comment]
I'm having the same issue after updating to 7.9.0. All regular users can login fine, but any user with the admin role gets "The application GUI just crashed." error. Admin users can login to the iOS app, but they're unable to access the admin settings page. I've already deleted all records in the banner and banner_dismiss collections, deleted the banner field from the user's record, etc...

I'm using OAuth, but I highly doubt that has anything to do with this. The issue seems specific to the admin role, not the login method. For example, if I remove the admin role and then reload the page, it loads fine. If I then add the admin role and reload, the page crashes.

**Comment by rmaksimov** [comment]
The same problem is on RC 7.9.3

**Comment by MarchRu** [comment]
I have the same issue, but there are no error logs in the console.

**Comment by reetp** [comment]
As per comments from internal support these are the basics you need to check first with this issue.

------------------

Do you have custom CSS, custom scripts or custom fields? Any of them can cause GUI to crash. 

If you have, try:

- copy
- remove
- restart server

Should work to pinpoint what is causing the crash.

**Comment by dip56245** [comment]
When I try login as admin I have some error (Application Error / The application GUI just crashed.):
- no errors in docker console
- error in JS
error:
`
verifyErrors.js:34 Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at uj (verifyErrors.js:34:1)
    at d (verifyErrors.js:34:1)
    at M (verifyErrors.js:34:1)
    at O (verifyErrors.js:34:1)
    at iD (verifyErrors.js:34:1)
    at s (verifyErrors.js:34:1)
    at us (verifyErrors.js:34:1)
    at ua (verifyErrors.js:34:1)
    at uo (verifyErrors.js:34:1)
    at s2 (verifyErrors.js:34:1)
ig @ verifyErrors.js:34
a.componentDidCatch.n.callback @ verifyErrors.js:34
as @ verifyErrors.js:34
sm @ verifyErrors.js:34
sO @ verifyErrors.js:34
sz @ verifyErrors.js:34
uc @ verifyErrors.js:34
ul @ verifyErrors.js:34
s6 @ verifyErrors.js:34
oz @ verifyErrors.js:34
(anonymous) @ verifyErrors.js:34
`


setup:
- Rocket.Chat Version: 7.12.1
- NodeJS Version: 22.16.0 - x64
- MongoDB Version: 8.0.4
- MongoDB Engine: wiredTiger
- Platform: linux 
- docker compose

now: 
- db.user(my user).banners <- empty
- db.user(my user).settings <- empty
- db.rocketchat_banner <- empty
- db.rocketchat_banner_dismiss <- empty
- No custom CSS/JS

**Comment by HelloJack0** [comment]
> I'm having the same issue after updating to 7.9.0. All regular users can login fine, but any user with the admin role gets "The application GUI just crashed." error. Admin users can login to the iOS app, but they're unable to access the admin settings page. I've already deleted all records in the banner and banner_dismiss collections, deleted the banner field from the user's record, etc...
> 
> I'm using OAuth, but I highly doubt that has anything to do with this. The issue seems specific to the admin role, not the login method. For example, if I remove the admin role and then reload the page, it loads fine. If I then add the admin role and reload, the page crashes.

8.0.1 still have the same issue, admin role

<img width="560" height="536" alt="Image" src="https://github.com/user-attachments/assets/4a348b94-6861-4a2e-b774-6c1c5e460332" />

**Comment by laarisyko** [comment]
Do you maybe have any idea how this could be solved or do we need to wait for an official patch?

**Comment by klepptor** [comment]
I just walked into the same issue on RC 8.5.3 (MongoDB 8.0), which was working fine for a about week. The error occured this afternoon on two different instances of RC nearly parallel...

**Comment by klepptor** [comment]
Ah, at least in my case it was a DNS problem. If the backend can't reach the RC servers the frontend fails with a nonsense error message.
