### ISSUE TITLE
Cannot find module '/client/polyfills/index.ts' in browser console

### ISSUE THREAD

**Issue by xmedeko** [RocketChat/Rocket.Chat#30784]
### Description:

I'am trying to upgrade from 6.2.10 to 6.4.4 according to https://docs.rocket.chat/deploy/deploy-rocket.chat/additional-deployment-methods/deploy-with-ubuntu Everything goes well, I start service OK. But when I go to URL I see progress indicator (three dots)  animating forever. When I open DevTools console, then I see an error:
```
url_common.js:80 Uncaught (in promise) Error: Cannot find module '/client/polyfills/index.ts'
    at y (url_common.js:80:1)
    at g (url_common.js:80:1)
    at d.r [as require] (url_common.js:80:1)
    at d.x [as link] (verifyErrors.js:34:1)
    at verifyErrors.js:34:1
    at dynamics_browser.js:74:1
```

Which is not happening with version 6.2.10.

### Server Setup Information:

- Version of Rocket.Chat Server: 6.4.4
- Operating System: Debian 10.13
- Deployment Method: tar https://docs.rocket.chat/deploy/deploy-rocket.chat/additional-deployment-methods/deploy-with-ubuntu 
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 14.21.3
- MongoDB Version: 4.4.13

### Client Setup Information

- Desktop App or Browser Version: Up to date Chrome or Firefox
- Operating System: Windows 11

**Comment by dominikandreas** [comment]
I had this issue first. What seemed to fix it for me was to update to 6.3.10 first, then to 6.4.5

**Comment by benji1000** [comment]
Hello, I am facing the very same issue. I am upgrading from a dockerized v5.4.10 of Rocket.chat. The upmost version I can upgrade to without this error is 6.3.10. As soon as I try to update to the 6.4.x branch, even the 6.4.0 version, the error appears.

**Comment by fuminori-ido-m** [comment]
Not working with the same error for me when upgrading from 6.3.10 to 6.4.5.

**Comment by tiger42** [comment]
I get the same error. I'm using the official Docker image. The latest working version is the 6.3.10.

**Comment by ranqiangjun** [comment]
The same

> I get the same error. I'm using the official Docker image. The latest working version is the 6.3.10.

**Comment by bzarzuela** [comment]
Same error and updating to 6.3.10 before 6.4.5 did not resolve the issue

**Comment by isaac82419** [comment]
I ran into this as well and I believe the problem is related to the site URL. I saw this error in my dev env which has a different URL. So I updated the site URL in mongo directly (see here: https://www.ryadel.com/en/rocket-chat-change-root_url-site-url-rocketchat/), I changed it to my dev env URL, and then when i started RC everything worked as expected.

**Comment by bzarzuela** [comment]
This works but there's a new issue which is most probably unrelated

Refused to execute https://<redacted>/meteor_runtime_config.js?hash=247e06aef78779ff69f880801dbd881bae7d44f2 as script because "X-Content-Type-Options: nosniff" was given and its Content-Type is not a script MIME type.

**Comment by fuminori-ido-m** [comment]
Thank you @isaac82419 , the linked page fixes my issue!
