### ISSUE TITLE
5.1.2 Crash with: error: TypeError: subscriptions.find is not a function

### ISSUE THREAD

**Issue by himpierre** [RocketChat/Rocket.Chat#26908]
### Description:

We run rocketchat with four replicas in a k8s cluster. Since upgrading to 5.1 (from 4.8) we have a lot of pod crashing. A problem which makes that even worse is the fact that the variable "EXIT_UNHANDLEDPROMISEREJECTION" does not seem to work anymore so one has to kill the pod by hand.

### Steps to reproduce:

1. Let rocketchat run for a while
2. Rocketchat gets unresponsive
3. Logfiles reveal a pod has crashed
4. Kill the pod to be able to use Rocketchat again

### Expected behavior:

Pods should not crash or at least when they crash they should exit enabling k8s to deploy a new container.

### Actual behavior:

Pod just hangs. Manual intervention is neccessary.

### Server Setup Information:

- Version of Rocket.Chat Server: 5.1.2
- Operating System: Linux
- Deployment Method: docker
- Number of Running Instances: 4
- DB Replicaset Oplog: sure
- NodeJS Version: 14.9.3
- MongoDB Version: 4.4.15

### Client Setup Information

- Desktop App or Browser Version: Any
- Operating System: Any

### Additional context

This is a EE installation. 

### Relevant logs:

```
{"level":50,"time":"2022-09-20T14:51:01.238Z","pid":1,"hostname":"rocketchat-nodejs-rocketchat-54cbc96d45-gwpcp","name":"OEmbed","msg":"Error fetching url content {}"}
=== UnHandledPromiseRejection ===
errorClass [Error]: [TypeError: subscriptions.find is not a function]
    at app/lib/server/lib/sendNotificationsOnMessage.js:392:11
    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40 {
  isClientSafe: true,
  error: TypeError: subscriptions.find is not a function
      at app/lib/server/lib/sendNotificationsOnMessage.js:377:41
      at Array.forEach (<anonymous>)
      at app/lib/server/lib/sendNotificationsOnMessage.js:376:11
      at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40,
  reason: undefined,
  details: undefined,
  errorType: 'Meteor.Error'
}
---------------------------------
Errors like this can cause oplog processing errors.
Setting EXIT_UNHANDLEDPROMISEREJECTION will cause the process to exit allowing your service to automatically restart the process
Future node.js versions will automatically exit the process
=================================
BadRequestError: request aborted
    at IncomingMessage.onAborted (/app/bundle/programs/server/npm/node_modules/meteor/simple_json-routes/node_modules/raw-body/index.js:231:10)
    at IncomingMessage.emit (events.js:400:28)
    at IncomingMessage.emit (domain.js:475:12)
    at abortIncoming (_http_server.js:569:9)
    at socketOnClose (_http_server.js:562:3)
    at Socket.emit (events.js:412:35)
    at Socket.emit (domain.js:475:12)
    at TCP.<anonymous> (net.js:686:12)
    at TCP.callbackTrampoline (internal/async_hooks.js:130:17)
BadRequestError: request aborted
    at IncomingMessage.onAborted (/app/bundle/programs/server/npm/node_modules/meteor/simple_json-routes/node_modules/raw-body/index.js:231:10)
    at IncomingMessage.emit (events.js:400:28)
    at IncomingMessage.emit (domain.js:475:12)
    at abortIncoming (_http_server.js:569:9)
    at socketOnClose (_http_server.js:562:3)
    at Socket.emit (events.js:412:35)
    at Socket.emit (domain.js:475:12)
    at TCP.<anonymous> (net.js:686:12)
    at TCP.callbackTrampoline (internal/async_hooks.js:130:17)
BadRequestError: request aborted
    at IncomingMessage.onAborted (/app/bundle/programs/server/npm/node_modules/meteor/simple_json-routes/node_modules/raw-body/index.js:231:10)
    at IncomingMessage.emit (events.js:400:28)
    at IncomingMessage.emit (domain.js:475:12)
    at abortIncoming (_http_server.js:569:9)
    at socketOnClose (_http_server.js:562:3)
    at Socket.emit (events.js:412:35)
    at Socket.emit (domain.js:475:12)
    at TCP.<anonymous> (net.js:686:12)
    at TCP.callbackTrampoline (internal/async_hooks.js:130:17)
BadRequestError: request aborted
    at IncomingMessage.onAborted (/app/bundle/programs/server/npm/node_modules/meteor/simple_json-routes/node_modules/raw-body/index.js:231:10)
    at IncomingMessage.emit (events.js:400:28)
    at IncomingMessage.emit (domain.js:475:12)
    at abortIncoming (_http_server.js:569:9)
    at socketOnClose (_http_server.js:562:3)
    at Socket.emit (events.js:412:35)
    at Socket.emit (domain.js:475:12)
    at TCP.<anonymous> (net.js:686:12)
    at TCP.callbackTrampoline (internal/async_hooks.js:130:17)
BadRequestError: request aborted
    at IncomingMessage.onAborted (/app/bundle/programs/server/npm/node_modules/meteor/simple_json-routes/node_modules/raw-body/index.js:231:10)
    at IncomingMessage.emit (events.js:400:28)
    at IncomingMessage.emit (domain.js:475:12)
    at abortIncoming (_http_server.js:569:9)
    at socketOnClose (_http_server.js:562:3)
    at Socket.emit (events.js:412:35)
    at Socket.emit (domain.js:475:12)
    at TCP.<anonymous> (net.js:686:12)
    at TCP.callbackTrampoline (internal/async_hooks.js:130:17)
```

**Comment by himpierre** [comment]
@debdutdeb Our systems crash twice a day. Can we have a release please?

**Comment by sampaiodiego** [comment]
hey @himpierre , version [5.1.3](https://github.com/RocketChat/Rocket.Chat/releases/tag/5.1.3) was published with a fix for this issue.

**Comment by himpierre** [comment]
Hi @sampaiodiego Thanks! Already installed!
