### ISSUE TITLE
SAML login not work after upgrade from 3.3.3 to 3.4.0. or 3.4.1

### ISSUE THREAD

**Issue by lichti** [RocketChat/Rocket.Chat#18166]
### Description:

After upgrade to 3.4.0 or 3.4.1 my users can't login in rocket.chat 
In log has a Exception:
```
I20200706-05:22:56.230(0) Exception while invoking method 'login' TypeError: (profile[roleAttributeName] || "").split is not a function
	at Function.mapProfileToUserObject (app/meteor-accounts-saml/server/lib/Utils.ts:454:83)
	at MethodInvocation.<anonymous> (app/meteor-accounts-saml/server/loginHandler.ts:30:32)
	at packages/accounts-base/accounts_server.js:462:31
	at tryLoginMethod (packages/accounts-base/accounts_server.js:1291:14)
	at AccountsServer._runLoginHandlers (packages/accounts-base/accounts_server.js:460:22)
	at AccountsServer.Accounts._runLoginHandlers (app/lib/server/lib/loginErrorMessageOverride.js:7:35)
	at MethodInvocation.methods.login (packages/accounts-base/accounts_server.js:520:31)
	at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)
	at packages/ddp-server/livedata_server.js:719:19
	at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
	at packages/ddp-server/livedata_server.js:717:46
	at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
	at packages/ddp-server/livedata_server.js:715:46
	at new Promise (<anonymous>)
	at Session.method (packages/ddp-server/livedata_server.js:689:23)
	at packages/ddp-server/livedata_server.js:559:43 
```

### Steps to reproduce:

1. Upgrade to 3.4.0 ou 3.4.1
2. Click in logon with SSO with SAML
3. Get an error

### Server Setup Information:

- Version of Rocket.Chat Server: 3.3.3 -> 3.4.0
- Operating System: Ubuntu 18.04
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: v12.16.3
- MongoDB Version:  v4.0.3

### Client Setup Information

- Desktop App or Browser Version: Both
- Operating System: MacOS

### Relevant logs:

```
I20200706-05:22:51.467(0) steffo:meteor-accounts-saml ➔ info {   actionName: 'authorize',   serviceName: 'idaptive',   credentialToken: 'id-xxx' } 
I20200706-05:22:51.467(0) steffo:meteor-accounts-saml ➔ info idaptive 
I20200706-05:22:51.470(0) steffo:meteor-accounts-saml ➔ info [   {     provider: 'idaptive',   .... } ] 
I20200706-05:22:51.471(0) steffo:meteor-accounts-saml ➔ info -----REQUEST------ 
I20200706-05:22:51.471(0) steffo:meteor-accounts-saml ➔ info <samlp:AuthnRequest xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" ID="id-.... 
I20200706-05:22:53.208(0) steffo:meteor-accounts-saml ➔ info {   actionName: 'validate',   serviceName: 'idaptive',   credentialToken: undefined } 
I20200706-05:22:53.208(0) steffo:meteor-accounts-saml ➔ info idaptive 
I20200706-05:22:53.209(0) steffo:meteor-accounts-saml ➔ info [   {     provider: 'idaptive',    ...  } ] 
I20200706-05:22:53.210(0) steffo:meteor-accounts-saml ➔ info Validating response with relay state: <?xml version="1.0" encoding="UTF-8"?><saml2p:Response ID="">...</saml2p:Response> 
I20200706-05:22:53.219(0) steffo:meteor-accounts-saml ➔ info Got response 
I20200706-05:22:53.223(0) steffo:meteor-accounts-saml ➔ info Verify status 
I20200706-05:22:53.224(0) steffo:meteor-accounts-saml ➔ info Status ok 
I20200706-05:22:53.225(0) steffo:meteor-accounts-saml ➔ info Verify Document Signature 
I20200706-05:22:53.226(0) steffo:meteor-accounts-saml ➔ info Failed to validate SAML signature: Signature not found 
I20200706-05:22:53.229(0) steffo:meteor-accounts-saml ➔ info Document Signature OK 
I20200706-05:22:53.230(0) steffo:meteor-accounts-saml ➔ info Verify Assertion Signature 
I20200706-05:22:53.246(0) steffo:meteor-accounts-saml ➔ info Assertion Signature OK 
I20200706-05:22:53.248(0) steffo:meteor-accounts-saml ➔ info Session Index: _861161eb-....-ed013819abb7 
I20200706-05:22:53.249(0) steffo:meteor-accounts-saml ➔ info Attribute Statement found in SAML response: <AttributeStatement xmlns="urn:oasis:names:tc:SAML:2.0:assertion">...</AttributeStatement> 
I20200706-05:22:53.250(0) steffo:meteor-accounts-saml ➔ info Attributes will be processed: 4 
I20200706-05:22:53.250(0) steffo:meteor-accounts-saml ➔ info Name:  <Attribute Name="username" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic" xmlns="urn:oasis:names:tc:SAML:2.0:assertion"><AttributeValue>....</AttributeValue></Attribute> 
I20200706-05:22:53.251(0) steffo:meteor-accounts-saml ➔ info Adding attribute from SAML response to profile: username = ...
I20200706-05:22:53.252(0) steffo:meteor-accounts-saml ➔ info Name:  <Attribute Name="email" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic" xmlns="urn:oasis:names:tc:SAML:2.0:assertion"><AttributeValue>....</AttributeValue></Attribute> 
I20200706-05:22:53.252(0) steffo:meteor-accounts-saml ➔ info Adding attribute from SAML response to profile: email = ...
I20200706-05:22:53.255(0) steffo:meteor-accounts-saml ➔ info Name:  <Attribute Name="cn" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic" xmlns="urn:oasis:names:tc:SAML:2.0:assertion"><AttributeValue>...</AttributeValue></Attribute> 
I20200706-05:22:53.255(0) steffo:meteor-accounts-saml ➔ info Adding attribute from SAML response to profile: cn = ...
I20200706-05:22:53.256(0) steffo:meteor-accounts-saml ➔ info Name:  <Attribute Name="chat-role" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic" xmlns="urn:oasis:names:tc:SAML:2.0:assertion">...</Attribute> 
I20200706-05:22:53.257(0) steffo:meteor-accounts-saml ➔ info Adding attribute from SAML response to profile: chat-role = ... 
I20200706-05:22:53.257(0) steffo:meteor-accounts-saml ➔ info NameID: {"inResponseToId":"id-...} 
I20200706-05:22:56.019(0) Meteor ➔ publish null -> userId: null, arguments: [] 
I20200706-05:22:56.227(0) steffo:meteor-accounts-saml ➔ info RESULT :{"profile":{"inResponseToId":"id-...} 
I20200706-05:22:56.229(0) steffo:meteor-accounts-saml ➔ info parsed userDataMap {   customFields: Map {},   attributeList: Set { 'username', 'email', 'cn' },   email: { fieldName: 'email' },   username: { fieldName: 'username' },   name: { fieldName: 'cn' },   identifier: { type: 'email' } } 
I20200706-05:22:56.230(0) Exception while invoking method 'login' TypeError: (profile[roleAttributeName] || "").split is not a function
	at Function.mapProfileToUserObject (app/meteor-accounts-saml/server/lib/Utils.ts:454:83)
	at MethodInvocation.<anonymous> (app/meteor-accounts-saml/server/loginHandler.ts:30:32)
	at packages/accounts-base/accounts_server.js:462:31
	at tryLoginMethod (packages/accounts-base/accounts_server.js:1291:14)
	at AccountsServer._runLoginHandlers (packages/accounts-base/accounts_server.js:460:22)
	at AccountsServer.Accounts._runLoginHandlers (app/lib/server/lib/loginErrorMessageOverride.js:7:35)
	at MethodInvocation.methods.login (packages/accounts-base/accounts_server.js:520:31)
	at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)
	at packages/ddp-server/livedata_server.js:719:19
	at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
	at packages/ddp-server/livedata_server.js:717:46
	at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
	at packages/ddp-server/livedata_server.js:715:46
	at new Promise (<anonymous>)
	at Session.method (packages/ddp-server/livedata_server.js:689:23)
	at packages/ddp-server/livedata_server.js:559:43 
I20200706-05:22:56.380(0) Meteor ➔ method loadLocale -> userId: null, arguments: ["pt-BR"] 
I20200706-05:22:56.526(0) Meteor ➔ method public-settings/get -> userId: null, arguments: [{}]
```
