### ISSUE TITLE
Users cannot search for channels they are not members of

### ISSUE THREAD

**Issue by kau210** [RocketChat/Rocket.Chat#8729]
### Description:

Users cannot search for (public) channels they are not members of. This appeared as an issue since the last upgrade, which we did about a week ago.
The bug has been reproduced on windows and linux desktop apps, on firefox, chrome and chromium web browsers.
When a user searches for a channel they are prompted with the create-channel page: https://domain.chat/create-channel
It is not a permission issue because if the user visits the channel (e.g. by visiting a link) they were trying to search they can join it.

Windows desktop app
![rc-search-channel-windows](https://user-images.githubusercontent.com/17986665/32227674-5120cf2a-be4c-11e7-9126-2e6ec0be9802.png)

Firefox on windows
![rc-search-channel-windows-firefox](https://user-images.githubusercontent.com/17986665/32231094-fe055460-be54-11e7-8da4-f0bf84f7d2df.png)

### Server Setup Information:

* Version of Rocket.Chat Server: 0.59.1
* Operating System: debian jessie
* Deployment Method(snap/docker/tar/etc): tar
* Number of Running Instances: 1
* DB Replicaset Oplog: disabled
* Node Version: 4.5

### Steps to Reproduce:

1. Make sure user is not a member of a public channel
2. Search for said public channel
3. Get suggestion to create a channel
4. (bonus step) Try creating a channel with that name and get error "Channel already exists".

### Expected Behavior
When we search for a public channel it should appear in the list below the search box.

### Actual behavior:
The user is given the option to create a channel and not to preview / join it.

**Comment by kajisaap** [comment]
We have 220+ member installation for Rocket.Chat and here's our configuration. 

### Server Setup Information:
* Version of Rocket.Chat Server: 0.59.3
* Operating System: Ubuntu 16.04.3
* Deployment Method(snap/docker/tar/etc): Docker
* Number of Running Instances: 1
* DB Replicaset Oplog: Yes
* Node Version: 

It is not happening to all the members but I can confirm this buggy behavior has been noticed and lodged in our internal support channels by few. I wonder if it has to do something with permission/role?

**Comment by kajisaap** [comment]
>It is not happening to all the members but I can confirm this buggy behavior has been noticed and lodged in our internal support channels by few. I wonder if it has to do something with permission/role?

It was definitely a permission matrix issue(people with administrative role did not encounter this behavior). We had our employees(users) of the rocket.chat automatically assume role **user** from RC administration page on permission. It was working fine in an earlier version(we were at 0.51). With 0.59.3, we had to add following to the permission to bring back the old behavior. 

<img width="668" alt="screen shot 2017-12-02 at 12 00 01 pm" src="https://user-images.githubusercontent.com/722803/33517788-5dcc347e-d758-11e7-9478-0a777ba9ebfc.png">

**Comment by kau210** [comment]
The was a glitch somewhere, but removing and adding the permissions and restarting made it work. So from my side we can close this issue! Thanks!
