### ISSUE TITLE
Notifications doesn't work after server update to 0.74.0

### ISSUE THREAD

**Issue by SupportAdar** [RocketChat/Rocket.Chat#13284]
### **My Setup**
Operating System: Windows 10 Professional 64bit 
App Version: 2.14.7(current version on Rocket.chat install menu)
Installation type: exe
Server: 0.74.0

### **Description**
I am using Rocket.Chat 2.14.7 on Windows 10. After update server from 0.72.0 to 0.74.0 notifications doesn't work anywhere eg. from web browser (Google Chrome) or from Windows Client 2.14.7 even "Test notification button" in user settings doesn't work.

Before update server to 0.74.0 notifications work well.

**Comment by Shaverdoff** [comment]
just now test on tar 074. push to mobile with apw and notification on desktop just arrived and work well. maybe in you environment have some missconfigurations?

**Comment by gabricom** [comment]
Same problem but solved. 
I was still using mongodb version 3.0 , and with 0.74.0 notifications stopped working.
Upgraded mongo to version 3.4 and now everything works fine.

**Comment by Shaverdoff** [comment]
hm...MongoDB shell version v3.6.8 is my instalation..

**Comment by TomaszDom** [comment]
Anybody experiencing a similar issue with Mongo 3.2? Which Mongo version are you running @SupportAdar ?

**Comment by sampaiodiego** [comment]
@SupportAdar can you please fill the setup details?

```
- Version of Rocket.Chat Server: 
- Operating System: 
- Deployment Method: <!-- snap/docker/tar/etc -->
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version: 
```

**Comment by SupportAdar** [comment]
Any advice before I'll start DB upgrade? I use this [tutorial](https://docs.mongodb.com/manual/tutorial/upgrade-revision/).

**Comment by Shaverdoff** [comment]
stop rocket stop mongo, yum/apt install, start mongo start rocket. this is was my steps then i am update. before procced ofcouse make snapshot vm/instance or something

**Comment by tzar** [comment]
Same issue here - downgrading to 0.73.2 seems to have brought the notifications back. I'm using the snap packaged version which I believe is running mongodb 3.2.x

**Comment by tassoevan** [comment]
"Test notification button" is broken (thanks @oguhpereira) and I'm investigating why.

**Comment by tzar** [comment]
It is actual notifications broken for us with 0.74.0 - I didn't try the test notification button; there were just client side javascript errors instead of notifications. So perhaps there are issues with both?

The reports above of fixing the issue by upgrading mongodb are interesting, does that mean that I need to wait for the rocketchat snap to also update mongodb past 3.2.x before upgrading again? Did some feature sneak in that needs minimum 3.4.x? Or is there documentation about how we are meant to deal with this case?

**Comment by sampaiodiego** [comment]
@tzar desktop notifications should not be broken, even on mongo 3.0 (which is not recommended anymore).

we'll need more details to address this issue.. can you please describe step by step when you expect to receive a notification and not receiving?

**Comment by Shaverdoff** [comment]
> 
> 
> @tzar desktop notifications should not be broken, even on mongo 3.0 (which is not recommended anymore).
> 
> we'll need more details to address this issue.. can you please describe step by step when you expect to receive a notification and not receiving?

3.0 not recommend... hm... and 3.6.8 is ok? notification works, but test notifications in 0741 do not owrks on 3.6.8 mongo in my deployment

**Comment by sampaiodiego** [comment]
@Shaverdoff yes, 3.6.8 is ok! `Test Notification` button is broken on 0.74.2. The fix will be released on 0.74.3.

**Comment by Shaverdoff** [comment]
Аmen! :) will wait new release

**Comment by TomaszDom** [comment]
@sampaiodiego will notifications work with mongo 3.2?

**Comment by tzar** [comment]
@sampaiodiego 

- I am using the packaged snap version of rocketchat server which seems to be bundled with mongo 3.2
- My users complained that they were not receiving any notifications when being mentioned or direct messaged and I verified that this was the case
- Downgrading rocketchat server to 0.73.2 caused the notifications to start working again
- There was a javascript error (minified so not much help - `Uncaught (in promise) TypeError: g is not a function`) instead of a notification
- One of our developers tried debugging it a bit and said they suspected it was connected to a failure to fetch avatars to show the notification

**Comment by sampaiodiego** [comment]
@TomaszDom yes, they will.

thanks for the infos @tzar .. I tried using the snap version as well, but notifications worked fine, as you can see in the video below:

![out-2](https://user-images.githubusercontent.com/8591547/52755836-77c69f80-2fe6-11e9-8584-e6158905b29b.gif)

was your test scenario like mine? what browsers (and versions) did you try?

**Comment by tzar** [comment]
@sampaiodiego hmm I only tested with chrome (71.0.3578.98) and rocketchat server is running on ubuntu LTS 16.04

The only real difference I can see is that you don't have any custom avatars set (we store ours on s3); if the issue is due to avatar loading this might mask it? If no luck I will have to find some downtime to re-upgrade it and see if I can find something more helpful.

**Comment by tassoevan** [comment]
@tzar It was the error I saw with "Test Desktop Notifications" button, fixed now by #13457. If the same error is throwed on browser's console when a notification is should be triggered then it is just a client side issue: no problem on Mongo layer at all.

**Comment by sampaiodiego** [comment]
guys the version 0.74.3 was just released including the mentioned fix. can you guys test it?

**Comment by tzar** [comment]
I don't think [it has been packaged as a snap yet](https://snapcraft.io/rocketchat-server) but will let you know how it goes once it is. Thanks!
