### ISSUE TITLE
 Rocketchat black screen after upgrade to 4.1

### ISSUE THREAD

**Issue by hamiteza** [RocketChat/Rocket.Chat#23906]
### Description:

Rocketchat  crashing in browser after upgrade from 4.0.6 to 4.1.1 ( and 4.1.2 and 4.2.0 )
Black screen after sign in 
### Steps to reproduce:

Applying rocketchat:4.0.6 with helm-chart in kubernetes cluster (helm pull --repo https://rocketchat.github.io/helm-charts rocketchat)
Update image.tag to 4.1.1 and apply again.

### Server Setup Information:

- Version of Rocket.Chat Server: 4.1.1
- Deployment Method: helm chart kubernetes
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: v12.22.1
- MongoDB Version: 4.4.6

### Client Setup Information

- Desktop App or Browser Version: Firefox 95.0
- Operating System: Ubuntu 20.04.2 LTS

### Additional context

I upgraded from 3.17.1 to 4.0.6 successfully

### Relevant logs:

BROWSER LOG:

Error: Cannot find module '@rocket.chat/fuselage-ui-kit'
    y https://chat-dev.kto.mci.dev/d1bd1327c436ca7b32d66a3e23754a2bdadd7979.js?meteor_js_resource=true:3
    resolve https://chat-dev.kto.mci.dev/d1bd1327c436ca7b32d66a3e23754a2bdadd7979.js?meteor_js_resource=true:3
    c https://chat-dev.kto.mci.dev/d1bd1327c436ca7b32d66a3e23754a2bdadd7979.js?meteor_js_resource=true:5
    module /client/views/banners/UiKitBanner.tsx:1
    i https://chat-dev.kto.mci.dev/d1bd1327c436ca7b32d66a3e23754a2bdadd7979.js?meteor_js_resource=true:732
    g https://chat-dev.kto.mci.dev/d1bd1327c436ca7b32d66a3e23754a2bdadd7979.js?meteor_js_resource=true:3
    n https://chat-dev.kto.mci.dev/d1bd1327c436ca7b32d66a3e23754a2bdadd7979.js?meteor_js_resource=true:3
    c https://chat-dev.kto.mci.dev/d1bd1327c436ca7b32d66a3e23754a2bdadd7979.js?meteor_js_resource=true:5
    module /client/views/banners/BannerRegion.tsx:1
    i https://chat-dev.kto.mci.dev/d1bd1327c436ca7b32d66a3e23754a2bdadd7979.js?meteor_js_resource=true:732
    g https://chat-dev.kto.mci.dev/d1bd1327c436ca7b32d66a3e23754a2bdadd7979.js?meteor_js_resource=true:3
    n https://chat-dev.kto.mci.dev/d1bd1327c436ca7b32d66a3e23754a2bdadd7979.js?meteor_js_resource=true:3
    c https://chat-dev.kto.mci.dev/d1bd1327c436ca7b32d66a3e23754a2bdadd7979.js?meteor_js_resource=true:5
    g https://chat-dev.kto.mci.dev/d1bd1327c436ca7b32d66a3e23754a2bdadd7979.js?meteor_js_resource=true:732
    dynamicImport https://chat-dev.kto.mci.dev/d1bd1327c436ca7b32d66a3e23754a2bdadd7979.js?meteor_js_resource=true:732
    bindEnvironment https://chat-dev.kto.mci.dev/d1bd1327c436ca7b32d66a3e23754a2bdadd7979.js?meteor_js_resource=true:1
d1bd1327c436ca7b32d66a3e23754a2bdadd7979.js:604:82936
    Ti https://chat-dev.kto.mci.dev/d1bd1327c436ca7b32d66a3e23754a2bdadd7979.js?meteor_js_resource=true:604
    callback https://chat-dev.kto.mci.dev/d1bd1327c436ca7b32d66a3e23754a2bdadd7979.js?meteor_js_resource=true:604
    Mc https://chat-dev.kto.mci.dev/d1bd1327c436ca7b32d66a3e23754a2bdadd7979.js?meteor_js_resource=true:604
    Li https://chat-dev.kto.mci.dev/d1bd1327c436ca7b32d66a3e23754a2bdadd7979.js?meteor_js_resource=true:604
    nf https://chat-dev.kto.mci.dev/d1bd1327c436ca7b32d66a3e23754a2bdadd7979.js?meteor_js_resource=true:604
    unstable_runWithPriority https://chat-dev.kto.mci.dev/d1bd1327c436ca7b32d66a3e23754a2bdadd7979.js?meteor_js_resource=true:622
    pc https://chat-dev.kto.mci.dev/d1bd1327c436ca7b32d66a3e23754a2bdadd7979.js?meteor_js_resource=true:604
    tf https://chat-dev.kto.mci.dev/d1bd1327c436ca7b32d66a3e23754a2bdadd7979.js?meteor_js_resource=true:604
    $s https://chat-dev.kto.mci.dev/d1bd1327c436ca7b32d66a3e23754a2bdadd7979.js?meteor_js_resource=true:604
    _c https://chat-dev.kto.mci.dev/d1bd1327c436ca7b32d66a3e23754a2bdadd7979.js?meteor_js_resource=true:604
    unstable_runWithPriority https://chat-dev.kto.mci.dev/d1bd1327c436ca7b32d66a3e23754a2bdadd7979.js?meteor_js_resource=true:622
    pc https://chat-dev.kto.mci.dev/d1bd1327c436ca7b32d66a3e23754a2bdadd7979.js?meteor_js_resource=true:604
    _c https://chat-dev.kto.mci.dev/d1bd1327c436ca7b32d66a3e23754a2bdadd7979.js?meteor_js_resource=true:604
    M https://chat-dev.kto.mci.dev/d1bd1327c436ca7b32d66a3e23754a2bdadd7979.js?meteor_js_resource=true:622
    onmessage https://chat-dev.kto.mci.dev/d1bd1327c436ca7b32d66a3e23754a2bdadd7979.js?meteor_js_resource=true:622

SERVER LOG: ( i dont know is relevant )

Error: ENOENT: no such file or directory, open '/tmp/userData/fZumW9mYGdyajhBFm/user.html'

    at Object.openSync (fs.js:462:3)

    at Object.writeFileSync (fs.js:1384:35)

    at startFile (app/user-data-download/server/cronProcessDownloads.js:39:5)

    at generateUserFile (app/user-data-download/server/cronProcessDownloads.js:410:2)

    at app/user-data-download/server/cronProcessDownloads.js:477:4

    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40 {

  errno: -2,

  syscall: 'open',

  code: 'ENOENT',

  path: '/tmp/userData/fZumW9mYGdyajhBFm/user.html'

}

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
