### ISSUE TITLE
Urgent Fix: Messages are not showing on channel page and unable to login

### ISSUE THREAD

**Issue by Tayyaba03** [RocketChat/Rocket.Chat#14701]
### Description:
When a user is logged out and opens a channel page, a white blank screen appears showing nothing, no messages and no option for the user to log in/sign in. As you can see in the attached screenshot list of public channels are also unavailable. 

### Steps to reproduce:
1. Go to directory page as a logged out user
2. Click on any channel  
3. A blank white screen appears without any messages or option to login

### Expected behavior:
As a logged out user channel page should show messages and at the bottom, a button appears which asks the user to log in or sign up.

### Actual behavior:
When a user is logged out and opens a channel page, a white blank screen appears showing nothing, no messages and no option for the user to log in/sign in.

<img width="913" alt="Screen Shot 2019-05-31 at 5 11 40 PM" src="https://user-images.githubusercontent.com/15376194/58683220-b7fc3300-83c7-11e9-9d99-368f2d855223.png">

### Server Setup Information:

- Version of Rocket.Chat Server: "1.1.1"
- Operating System: linux
- Number of Running Instances: 1
- NodeJS Version: v8.11.4
- MongoDB Version: 3.4.19

### Additional context
Giving 400 error in the console 
`/api/v1/groups.members?roomName=mods`
however, we don't have any room with the name "mods"
Unable to revert to the previous version because while doing it gives the error that we have migrated your database to the latest version

### Relevant logs:
Can't share logs as I'm unable to login back :(

Please solve it as soon as you guys can. 

Thank you

**Comment by tassoevan** [comment]
Does your browser console log any errors?

**Comment by Tayyaba03** [comment]
@tassoevan the one I mentined in 
**Additional context**
Giving 400 error in the console
`/api/v1/groups.members?roomName=mods`

and the followings:

`Couldn't load members
ice.js:1 Failed to log to loggly because of this exception:
TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Window'
    --- property 'parent' closes the circle`

`Failed log data: 
{args: Arguments(2), stack: undefined, url: "https://urlofoursite", ua: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) Ap…L, like Gecko) Chrome/74.0.3729.169 Safari/537.36", v: "1655.008-2.056", …}
args: Arguments(2)
0: "CatchAll. Exception: $ice.$root.browser.getDevice is not a function"
1: Window {postMessage: ƒ, blur: ƒ, focus: ƒ, close: ƒ, parent: Window, …}`

**Comment by fais3000** [comment]
This is happening when Anonymous read is on.

**Comment by Tayyaba03** [comment]
@tassoevan any update on this one?

**Comment by sampaiodiego** [comment]
are you guys able to test https://github.com/RocketChat/Rocket.Chat/pull/14717 ?
I can provide a Docker image if that makes it easy for testing. thx

**Comment by fais3000** [comment]
@sampaiodiego Tested in 1.1.2. Still broken, same behavior as prior version.

**Comment by sampaiodiego** [comment]
@fais3000 in wihch browser are you having the issue? can you please describe detailed what you are doing and what are you seeing? thanks

**Comment by fais3000** [comment]
@sampaiodiego Chrome and Firefox. When users visits a public channel when anonymous read is on. e.g https://chat.talkwithstranger.com/channel/chatroom The page fails to load and is still with the loading spinner. 

- Same happens if this url is used in an iframe
- Same happens on a mobile browser (safari)

We had to disable anonymous read for now. It used to work on 1.0.3 and prior versions with same setup.

Here is a screenshot one user shared
![image](https://user-images.githubusercontent.com/25720059/59889176-3e33f400-941f-11e9-92f1-fec31e166a0f.png)

**Comment by sampaiodiego** [comment]
@fais3000 I just tested on either 1.0.3 and 0.74.3 and both versions didn't work when trying to access the room URL **directly** (i.e.: http://localhost:3000/channel/general)..

but they both work if you go *first* to home page (i.e.: http://localhost:3000/home) and then open the channel you want via UI.

I'll create an issue so we can fix this for the next version.
