### ISSUE TITLE
Custom oAuth stoped working after upgrade to 0.49

### ISSUE THREAD

**Issue by Perksls** [RocketChat/Rocket.Chat#5519]
Your Rocket.Chat version: (0,49), after upgrade to the 0,49 the custom oAuth stoped working
`Exception while invoking method 'login' TypeError: fun is not a function   at Resultset.find (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/rocketchat_lib/node_modules/lokijs/src/lokijs.js:2197:17)   at Resultset.findAnd (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/rocketchat_lib/node_modules/lokijs/src/lokijs.js:1965:14)   at Resultset.find (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/rocketchat_lib/node_modules/lokijs/src/lokijs.js:2038:53)   at new Resultset (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/rocketchat_lib/node_modules/lokijs/src/lokijs.js:1462:21)   at LokiEventEmitter.Collection.findOne (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/rocketchat_lib/node_modules/lokijs/src/lokijs.js:4232:20)   at ModelsBaseCache.findOne (/opt/Rocket.Chat/programs/server/packages/rocketchat_lib.js:7965:60)   at ModelsBaseCache.target.(anonymous function) [as findOne] (/opt/Rocket.Chat/programs/server/packages/rocketchat_lib.js:7066:30)   at ModelsBaseCache.update (/opt/Rocket.Chat/programs/server/packages/rocketchat_lib.js:8241:66)   at ModelsBaseCache.target.(anonymous function) [as update] (/opt/Rocket.Chat/programs/server/packages/rocketchat_lib.js:7066:30)   at ModelsBaseDb.<anonymous> (/opt/Rocket.Chat/programs/server/packages/rocketchat_lib.js:7690:14)   at emitOne (events.js:77:13)   at ModelsBaseDb.emit (events.js:169:7)   at ModelsBaseDb.update (/opt/Rocket.Chat/programs/server/packages/rocketchat_lib.js:8635:11)   at ModelUsers.update (/opt/Rocket.Chat/programs/server/packages/rocketchat_lib.js:3569:36)   at ModelUsers.setEmailVerified (/opt/Rocket.Chat/programs/server/packages/rocketchat_lib.js:6755:17)   at AccountsServer.Accounts.updateOrCreateUserFromExternalService (/opt/Rocket.Chat/programs/server/app/app.js:4505:31)   at [object Object].<anonymous> (packages/accounts-oauth.js:133:21)   at /opt/Rocket.Chat/programs/server/packages/accounts-base.js:938:30   at tryLoginMethod (/opt/Rocket.Chat/programs/server/packages/accounts-base.js:763:14)   at AccountsServer.Ap._runLoginHandlers (/opt/Rocket.Chat/programs/server/packages/accounts-base.js:937:18)   at [object Object].methods.login (/opt/Rocket.Chat/programs/server/packages/accounts-base.js:994:27)   at maybeAuditArgumentChecks (/opt/Rocket.Chat/programs/server/packages/ddp-server.js:2108:12)   at /opt/Rocket.Chat/programs/server/packages/ddp-server.js:1042:22   at [object Object]._.extend.withValue (packages/meteor.js:1122:17)   at /opt/Rocket.Chat/programs/server/packages/ddp-server.js:1041:43   at [object Object]._.extend.withValue (packages/meteor.js:1122:17)   at /opt/Rocket.Chat/programs/server/packages/ddp-server.js:1040:48   at Session.method (/opt/Rocket.Chat/programs/server/packages/ddp-server.js:1018:23)   at /opt/Rocket.Chat/programs/server/packages/ddp-server.js:880:89 `

edit: sorry, its duplicate from issue [5516](https://github.com/RocketChat/Rocket.Chat/issues/5516) although in 5516 it's mentioned only facebook oAuth

**Comment by engelgabriel** [comment]
Dup https://github.com/RocketChat/Rocket.Chat/issues/5511

**Comment by geekgonecrazy** [comment]
Going to go ahead and keep #5536 as to tracking this specific issue, as #5511 seems to be redirect URI.
