### ISSUE TITLE
RocketChat.SlackBridge.importMessages is not a function

### ISSUE THREAD

**Issue by nedbase-jesse** [RocketChat/Rocket.Chat#11356]
### Description:

I have enabled the SlackBridge to sync messages between Slack and RocketChat. Normally after an upgrade of RocketChat I run /slackbridge-import in the channels I am part of. So the messages are synced back.
After the upgrade to 0.66.1 from 0.65.2 I received the following message:
SlackBridge got an error while importing your messages at `<channel>`: RocketChat.SlackBridge.importMessages is not a function

### Steps to reproduce:

1. Go to any channel that is synced with Slack
2. Type /slackbridge-import
3. Hit enter

### Expected behavior:

It imports the messages from Slack that are not in RocketChat

### Actual behavior:

Received the error:
SlackBridge got an error while importing your messages at `<channel>`: RocketChat.SlackBridge.importMessages is not a function

### Server Setup Information:

- Version of Rocket.Chat Server: 0.66.1
- Operating System: CoreOS / Kubernetes
- Deployment Method: Kubernetes / Docker
- Number of Running Instances: 1
- DB Replicaset Oplog: false
- NodeJS Version: 8.11.3
- MongoDB Version: 2.1.19

### Relevant logs:
`Exception while invoking method 'slashCommand' TypeError: RocketChat.SlackBridge.importMessages is not a function     at Object.SlackBridgeImport [as callback] (/app/bundle/programs/server/packages/rocketchat_slackbridge.js:250:28)     at Object._runningSlashCommand [as run] (/app/bundle/programs/server/packages/rocketchat_lib.js:1757:55)     at MethodInvocation.slashCommand (/app/bundle/programs/server/packages/rocketchat_lib.js:1812:37)     at MethodInvocation.methodsMap.(anonymous function) (/app/bundle/programs/server/packages/rocketchat_lib.js:2428:36)     at MethodInvocation.methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)     at maybeAuditArgumentChecks (/app/bundle/programs/server/packages/ddp-server.js:1877:12)     at DDP._CurrentMethodInvocation.withValue (/app/bundle/programs/server/packages/ddp-server.js:902:126)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:12)     at DDPServer._CurrentWriteFence.withValue (/app/bundle/programs/server/packages/ddp-server.js:902:98)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:12)     at Promise (/app/bundle/programs/server/packages/ddp-server.js:902:46)     at new Promise (<anonymous>:null:null)     at Session.method (/app/bundle/programs/server/packages/ddp-server.js:875:23)     at /app/bundle/programs/server/packages/ddp-server.js:754:85`

**Comment by nedbase-jesse** [comment]
Still in version 0.68.4

**Comment by JulioC** [comment]
Also affects 0.69.2

**Comment by kevin-og** [comment]
Same behavior in 0.70.4

**Comment by lazyants** [comment]
+1

**Comment by nylen** [comment]
Still an issue in 0.71.1

**Comment by esolitos** [comment]
I can confirm, still happening on: `0.72.3`

**Comment by nedbase-jesse** [comment]
@geekgonecrazy is this on your radar?

**Comment by geekgonecrazy** [comment]
Not mine specifically.. I don’t do much with importers.

@Hudell maybe on yours?

**Comment by vwbusguy** [comment]
Still an issue on 0.74.2

**Comment by esolitos** [comment]
Anything we can help with?

I see that [the call](https://github.com/RocketChat/Rocket.Chat/blob/0.74.3/packages/rocketchat-slackbridge/server/slackbridge_import.server.js#L28) is against `SlackBridge`, however the methoid `importMessages` is implemented [on the Adapter](https://github.com/RocketChat/Rocket.Chat/blob/0.74.3/packages/rocketchat-slackbridge/server/SlackAdapter.js#L1120).

Just a wild guess, could be the fix as easy as that? :)

**Comment by geekgonecrazy** [comment]
We take PRs!  :) it definitely could be as easy as that.

**Comment by rodrigok** [comment]
Closed via https://github.com/RocketChat/Rocket.Chat/pull/14273
