### ISSUE TITLE
Error: Cannot find module 'fibers' when upgrading to Rocket.Chat 0.14

### ISSUE THREAD

**Issue by improvethings** [RocketChat/Rocket.Chat#1975]
~/Rocket.Chat$ node main.js

module.js:340
    throw err;
          ^
Error: Cannot find module 'fibers'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/geek/Rocket.Chat/programs/server/boot.js:1:75)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

**Comment by improvethings** [comment]
Resolution: 
(cd programs/server && npm install)

**Comment by marceloschmidt** [comment]
@Sing-Li @MuhClaren Should we add this to docs? Is this required after each update?

**Comment by engelgabriel** [comment]
@improvethings how did you perform the upgrade? Did you download the ZIP file from https://rocket.chat/releases ?

**Comment by improvethings** [comment]
I followed step 5 of: 
https://github.com/RocketChat/Rocket.Chat/wiki/Deploy-Rocket.Chat-without-docker

(removed the previous version, and did curl -L https://rocket.chat/releases/latest/download -o rocket.chat.tgz)

**Comment by engelgabriel** [comment]
Did you do the "4. Repeat Installation step"??

**Comment by engelgabriel** [comment]
The "Installation Step" has: 
```
mv bundle Rocket.Chat
cd Rocket.Chat/programs/server
npm install
cd ../..
```

**Comment by kyrogue** [comment]
its not a must to rename it to Rocket.Chat right?

**Comment by himito** [comment]
@kyrogue  no

**Comment by SteffanCline** [comment]
I too an having this same error on CentOS 7. Node is 8.9.3. I followed the direction above to npm install again but get these errors.

`npm ERR! Linux 4.15.10-1.el7.elrepo.x86_64
npm ERR! argv "/usr/local/bin/node" "/usr/bin/npm" "install"
npm ERR! node v8.9.3
npm ERR! npm  v3.10.10
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! fibers@2.0.0 install: `node build.js || nodejs build.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the fibers@2.0.0 install script 'node build.js || nodejs build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the fibers package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build.js || nodejs build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs fibers
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls fibers
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/html/rocket.chat/programs/server/npm-debug.log`

Is there a newer repo for npmand node.js than what is in epel?

**Comment by disaster123** [comment]
Same again with current 1.1.1 release - downloaded from https://releases.rocket.chat/latest/download

**Comment by alleait** [comment]
i have the same issue with verison 3.0.2 i am running nodejs 12.16.1 


Feb 27 11:40:56 chat rocketchat[679]: Error: Cannot find module '/opt/Rocket.Chat/programs/server/node_modules/fibers/bin/linux-x64-57-glibc/fibers'
Feb 27 11:40:56 chat rocketchat[679]:     at Function.Module._resolveFilename (module.js:548:15)
Feb 27 11:40:56 chat rocketchat[679]:     at Function.Module._load (module.js:475:25)
Feb 27 11:40:56 chat rocketchat[679]:     at Module.require (module.js:597:17)
Feb 27 11:40:56 chat rocketchat[679]:     at require (internal/module.js:11:18)
Feb 27 11:40:56 chat rocketchat[679]:     at Object.<anonymous> (/opt/Rocket.Chat/programs/server/node_modules/fibers/fibers.js:14:39)
Feb 27 11:40:56 chat rocketchat[679]:     at Module._compile (module.js:653:30)

Looks like rocketchat looks for fibers in a  folder that no longer exists .

**Comment by sotoplatero** [comment]
same issue with verison 3.0.3 i am running nodejs 12.16.1

**Comment by sotoplatero** [comment]
I resolved with

``` 
sudo npm install -g inherits n && sudo n 12.14.0 
```

It is one of the steps of the installation guide https://rocket.chat/docs/installation/manual-installation/ubuntu/

**Comment by alleait** [comment]
@sotoplatero  doesn't solve it for me i already have correct node version .

**Comment by kvaps** [comment]
same here, release from https://releases.rocket.chat/latest/download

**Comment by amoebav** [comment]
Same here when upgrading to v3 from v2.2: https://github.com/RocketChat/Rocket.Chat/issues/16611#issuecomment-674127306
