### ISSUE TITLE
Integrations: Incoming Webhook - Super globals not working

### ISSUE THREAD

**Issue by j-stahl** [RocketChat/Rocket.Chat#28973]
### Description:

After upgrading Rocket.Chat from 4.8.3 to 6.1.3 our Webhook Script did not work anymore. Before upgrading the Webhook script was working as expected.

### Steps to reproduce:

1. Go to Integration Webhooks
2. Create a Webhook
3. Insert a script, which is using the super global `s`:
```
let text = 'my funny demo text without any sence';
text=s(text).replaceAll(' ','_').strLeft('text').value();
```
4. Curl the webhook

### Expected behavior:

Push the notification to the chat room!

### Actual behavior:

Nothing happens
Rocket.Chat container logs:
```
... long message ... ,"msg":"TypeError: s is not a function"}
```

### Server Setup Information:

- Version of Rocket.Chat Server: 6.1.3
- Operating System: Ubuntu 20
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 12.21.2
- MongoDB Version: 4.4.10

### Workaround:
I am currently not using the super global s anymore.

### Possible solutions:
* Fix it in a way the super global work as in does earlier versions of RC
* Remove its usage from documentation: https://docs.rocket.chat/use-rocket.chat/workspace-administration/integrations
