### PR TITLE
fix: pass missing BlockContext argument to renderTextObject in Sectio…

### LINKED ISSUE #39493: fix: Missing BlockContext argument in renderTextObject call in SectionBlock
### Description:

After the refactor in #39268 (refactor(ui-kit): Remove UiKit deprecations), 
the `renderTextObject` call in `SectionBlock.tsx` is missing its required 
third `context` argument, causing a TypeScript build error on the develop branch.

### Steps to reproduce:

1. Clone the repo and checkout develop
2. Run yarn dev
3. Observe the TypeScript error in @rocket.chat/fuselage-ui-kit compilation

### Expected behavior:

@rocket.chat/fuselage-ui-kit compiles with 0 errors

### Actual behavior:

src/blocks/SectionBlock.tsx:31:24 - error TS2554: Expected 3 arguments, but got 2.

31   {surfaceRenderer.renderTextObject(text, 0)}

renderTextObject requires: (textObject: TextObject, index: number, context: BlockContext)
An argument for 'context' was not provided.

### Server Setup Information:

- Version of Rocket.Chat Server: 8.3.0-develop
- License Type: Community
- Number of Users: 
- Operating System: Ubuntu
- Deployment Method: Local development
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 22.16.0
- MongoDB Version: 8.0

### Client Setup Information

- Desktop App or Browser Version: Chrome
- Operating System: Ubuntu

### Additional context

Introduced by commit 87f9262af4 which replaced surfaceRenderer.text(text) 
with surfaceRenderer.renderTextObject(text, 0) but omitted the required 
third argument. Every other call to renderTextObject in the codebase 
correctly passes UiKit.BlockContext.NONE as the third argument 
(see ButtonElement.tsx, CalloutBlock.tsx, InputBlock.tsx etc).

Also requires changing the import from `import type * as UiKit` to 
`import * as UiKit` since BlockContext is a runtime const, not a type.

### Relevant logs:

N/A

### PR DESCRIPTION
**Pull request by SamarthShukla17**
## Proposed changes (including videos or screenshots)

`renderTextObject` in `SectionBlock.tsx` was being called with 2 arguments 
instead of the required 3 after the refactor in #39268. This caused a 
TypeScript build error on develop.

Changes:
- Pass `UiKit.BlockContext.NONE` as the third argument to `renderTextObject`
- Change `import type * as UiKit` to `import * as UiKit` since `BlockContext` 
  is a runtime const object, not just a type

## Issue(s)

Closes #39493 

## Steps to test or reproduce

1. Checkout this branch
2. Run `yarn dev`
3. Verify `@rocket.chat/fuselage-ui-kit` compiles with 0 errors
   (previously showed: error TS2554: Expected 3 arguments, but got 2)

## Further comments

Every other call to `renderTextObject` in the codebase already passes 
`UiKit.BlockContext.NONE` as the third argument — see `ButtonElement.tsx`, 
`CalloutBlock.tsx`, `InputBlock.tsx` etc. This brings `SectionBlock.tsx` 
in line with the rest.

## Bug Fixes
* Fixed a rendering issue where section block text objects were not properly receiving required context information during text processing. This fix resolves potential display inconsistencies and ensures proper functionality across text rendering operations. The patch ensures that all text elements display correctly and behave consistently throughout the UI Kit library and its components.

### CODE REVIEW

File: packages/fuselage-ui-kit/src/blocks/SectionBlock.tsx [hunk 1]
```diff
@@ -28,7 +28,7 @@ const SectionBlock = ({ className, block, surfaceRenderer }: SectionBlockProps):
 			<GridItem>
 				{text && (
 					<Box is='span' fontScale='p2' color='default'>
-						{surfaceRenderer.renderTextObject(text, 0)}
+						{surfaceRenderer.renderTextObject(text, 0, UiKit.BlockContext.NONE)}
 					</Box>
```
[the remark this answers is not in the document]
Comment (SamarthShukla17) [reply packages/fuselage-ui-kit/src/blocks/SectionBlock.tsx:32]: Thanks for the suggestion! However, every other block in this codebase 
(`CalloutBlock.tsx`, `InputBlock.tsx`, `ImageBlock.tsx`, `ActionsBlock.tsx`, 
`PreviewBlock.tsx`, `InfoCard.tsx`, and even `SectionBlock.Fields.tsx`) 
uses `BlockContext.NONE` for `renderTextObject` calls. Using `BlockContext.NONE` 
keeps this consistent with the rest of the codebase.
