### ISSUE TITLE
Rocket.Chat (4.7.1) not working on Yandex browser

### ISSUE THREAD

**Issue by sviat9440** [RocketChat/Rocket.Chat#25600]
### Description:

When launch Rocket.Chat on Yandex browser, I see a black screen and a lot of errors in the console

### Steps to reproduce:

1. Open Rocket.Chat in Yandex browser

### Expected behavior:

Everything works as before

### Actual behavior:

Web client crashed

![image](https://user-images.githubusercontent.com/13107421/169779327-05c4d2b7-ed6d-460a-8eac-56dfb19ef40f.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 4.7.1
- Operating System: 
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: v14.18.3
- MongoDB Version: 4.2.20

### Client Setup Information

- Desktop App or Browser Version: Browser Version
- Operating System: Windows 11

### Relevant logs:

```
9a19deca40b3b34350b0c5e4c4ec2d702791cdc7.js?meteor_js_resource=true:1092 TypeError: r is not a function
    at eval (/client/sidebar/hooks/useShortcutOpenMenu.js:1:219)
    at df (9a19deca40b3b34350b0c5e4c4ec2d702791cdc7.js?meteor_js_resource=true:1092:104532)
    at t.unstable_runWithPriority (9a19deca40b3b34350b0c5e4c4ec2d702791cdc7.js?meteor_js_resource=true:1110:3778)
    at _a (9a19deca40b3b34350b0c5e4c4ec2d702791cdc7.js?meteor_js_resource=true:1092:45381)
    at ff (9a19deca40b3b34350b0c5e4c4ec2d702791cdc7.js?meteor_js_resource=true:1092:103995)
    at 9a19deca40b3b34350b0c5e4c4ec2d702791cdc7.js?meteor_js_resource=true:1092:103906
    at R (9a19deca40b3b34350b0c5e4c4ec2d702791cdc7.js?meteor_js_resource=true:1110:2838)
    at MessagePort.v.port1.onmessage (9a19deca40b3b34350b0c5e4c4ec2d702791cdc7.js?meteor_js_resource=true:1110:1561)
Fi @ 9a19deca40b3b34350b0c5e4c4ec2d702791cdc7.js?meteor_js_resource=true:1092

9a19deca40b3b34350b0c5e4c4ec2d702791cdc7.js?meteor_js_resource=true:1092 TypeError: k is not a function
    at eval (/client/sidebar/header/actions/Search.tsx:1:755)
    at df (9a19deca40b3b34350b0c5e4c4ec2d702791cdc7.js?meteor_js_resource=true:1092:104532)
    at t.unstable_runWithPriority (9a19deca40b3b34350b0c5e4c4ec2d702791cdc7.js?meteor_js_resource=true:1110:3778)
    at _a (9a19deca40b3b34350b0c5e4c4ec2d702791cdc7.js?meteor_js_resource=true:1092:45381)
    at ff (9a19deca40b3b34350b0c5e4c4ec2d702791cdc7.js?meteor_js_resource=true:1092:103995)
    at 9a19deca40b3b34350b0c5e4c4ec2d702791cdc7.js?meteor_js_resource=true:1092:103906
    at R (9a19deca40b3b34350b0c5e4c4ec2d702791cdc7.js?meteor_js_resource=true:1110:2838)
    at MessagePort.v.port1.onmessage (9a19deca40b3b34350b0c5e4c4ec2d702791cdc7.js?meteor_js_resource=true:1110:1561)
Fi @ 9a19deca40b3b34350b0c5e4c4ec2d702791cdc7.js?meteor_js_resource=true:1092

9a19deca40b3b34350b0c5e4c4ec2d702791cdc7.js?meteor_js_resource=true:1110 Uncaught TypeError: r is not a function
    at eval (/client/sidebar/hooks/useShortcutOpenMenu.js:1:219)
    at df (9a19deca40b3b34350b0c5e4c4ec2d702791cdc7.js?meteor_js_resource=true:1092:104532)
    at t.unstable_runWithPriority (9a19deca40b3b34350b0c5e4c4ec2d702791cdc7.js?meteor_js_resource=true:1110:3778)
    at _a (9a19deca40b3b34350b0c5e4c4ec2d702791cdc7.js?meteor_js_resource=true:1092:45381)
    at ff (9a19deca40b3b34350b0c5e4c4ec2d702791cdc7.js?meteor_js_resource=true:1092:103995)
    at 9a19deca40b3b34350b0c5e4c4ec2d702791cdc7.js?meteor_js_resource=true:1092:103906
    at R (9a19deca40b3b34350b0c5e4c4ec2d702791cdc7.js?meteor_js_resource=true:1110:2838)
    at MessagePort.v.port1.onmessage (9a19deca40b3b34350b0c5e4c4ec2d702791cdc7.js?meteor_js_resource=true:1110:1561)

9a19deca40b3b34350b0c5e4c4ec2d702791cdc7.js?meteor_js_resource=true:1386 Uncaught (in promise) undefined
```

**Comment by IKrendelev** [comment]
Confirm on 4.7.1.
Same error on two different deployments.

**Comment by sashakotljarov** [comment]
Rocket.Chat (4.8.0-rc.0) not working on Yandex browser (22.5.0.1814 (64-bit))

**Comment by sviat9440** [comment]
@dudanogueira any reaction?

**Comment by sashakotljarov** [comment]
> any reaction?

I created a ticket for Yandex. Probably a browser issue, not a server issue.

**Comment by sviat9440** [comment]
> > any reaction?
> 
> I created a ticket for Yandex. Probably a browser issue, not a server issue.

Ok. Please keep us informed.

**Comment by ankar84** [comment]
Confirm that on 4.8.1


> Probably a browser issue, not a server issue.

Agree with you!

**Comment by nvkzshadow** [comment]
Having that issue too. I've created ticket to browser@support.yandex.ru

**Comment by sviat9440** [comment]
@nvkzshadow Can you explain what exactly doesn't work in yandex browser?

**Comment by sashakotljarov** [comment]
> Can you explain what exactly doesn't work in yandex browser?

https://drive.google.com/file/d/16vmsCRGfQWVlSZo3ai-gVyzgsWFZloKS/view?usp=sharing

**Comment by sviat9440** [comment]
> > Can you explain what exactly doesn't work in yandex browser?
> 
> https://drive.google.com/file/d/16vmsCRGfQWVlSZo3ai-gVyzgsWFZloKS/view?usp=sharing

No, that's not what I meant. I've seen these errors. I meant: why do these errors appear? What should I get a ticket for?

**Comment by q00Dree** [comment]
Have the same issue. Any updates? Just black screen...

**Comment by mredrake** [comment]
The problem is gone on Yandex Browser 22.5.4.904 after switching to Chrome UA. 
In other hand, the problem is reproducing on Chrome after switching to Yandex Browser UA (grey screen, errors on console)

This is a server issue.

**Comment by sashakotljarov** [comment]
Yandex is working on a solution to the problem. 
Yandex offered a temporary solution... In the Yandex browser shortcut, the "object" section, add an entry of the form: --user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36"

The result should look like this (spaces are required):
C:\Users\%username%\AppData\Local\Yandex\YandexBrowser\Application\browser.exe --user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36"

Checked, it works

**Comment by sashakotljarov** [comment]
As Yandex browser support reports, there is a problem with the rocket chat server. It is with the user-agent of the Yandex browser that the problem arises. Even if you specify it in google chrome, the chat will not work either

**Comment by sviat9440** [comment]
any updates?

**Comment by sviat9440** [comment]
up

**Comment by sviat9440** [comment]
version: 5.0.1

**Comment by sviat9440** [comment]
any updates?

**Comment by mikesrus** [comment]
still not working 4.8.3

**Comment by kholoshnia** [comment]
We are running into the same issue when trying to use Rocket.Chat 5.0.4 inside iOS [WKWebView](https://developer.apple.com/documentation/webkit/wkwebview).

When the meteor is started from the `apps/meteor` directory with the `yarn start` command, we can see the unminified missing function name:

<img width="500" alt="screenshot" src="https://user-images.githubusercontent.com/52531614/193567792-a8c8ce09-c2f1-4f86-9acf-616f4438b989.png">

The [tinykeys](https://jamiebuilds.github.io/tinykeys) library function was not found inside these files: \
https://github.com/RocketChat/Rocket.Chat/blob/5.0.4/apps/meteor/client/sidebar/hooks/useShortcutOpenMenu.ts#L7 \
https://github.com/RocketChat/Rocket.Chat/blob/5.0.4/apps/meteor/client/sidebar/header/actions/Search.tsx#L23

It looks like these errors occur when the browser sets some kind of unpopular or invalid User-Agent header.

**Comment by mikesrus** [comment]
for me workaround is replace user agent on nginx reverse proxy for users

**Comment by IKrendelev** [comment]
Ugly, bad and generally non-recommended, but 100%-guaranteed workaround about Yandex.Browser:
![image](https://user-images.githubusercontent.com/103184392/195592261-c4ff5f0f-4b7e-43ea-bca9-6c8ba93515b5.png)

**Comment by azhinu** [comment]
Using this with Caddy
```
reverse_proxy rocketchat-app:3000 {
		header_up User-Agent "Linux.*YaBrowser" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
		header_up User-Agent "Macintosh.*YaBrowser" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36"
		header_up User-Agent "Windows.*YaBrowser" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
	}
```

**Comment by supermike** [comment]
> Ugly, bad and generally non-recommended, but 100%-guaranteed workaround about Yandex.Browser: ![image](https://user-images.githubusercontent.com/103184392/195592261-c4ff5f0f-4b7e-43ea-bca9-6c8ba93515b5.png)

The changed user-agent did not help. All hope is for your solution. I made this code edit, but nothing has changed, the browser is marked as not modern. Is it necessary to make any additional operations after changing the code, such as App Rebuid/Restart?

**Comment by IKrendelev** [comment]
> > Ugly, bad and generally non-recommended, but 100%-guaranteed workaround about Yandex.Browser:<...>
> 
> The changed user-agent did not help. All hope is for your solution. I made this code edit, but nothing has changed, the browser is marked as not modern. Is it necessary to make any additional operations after changing the code, such as App Rebuid/Restart?

As I remember, I've restarted docker containers by `docker-compose down && docker-compose up -d` and have cleared application cache on the client side (seems that it's done periodically in automatic mode, but I had to get sure quickly).

**Comment by Andefraim** [comment]
The app must not rely on UA anymore. Other ways to determine browser capabilities should be used instead. Btw there are polyfills to make older browsers work. The modern Yandex Browser must not have any issues due to its UA.

**Comment by way2song** [comment]
Hello team. 6.2.2 The bug is saved.
Still doesn't work in Ya.Browser
Please resolving this issue please

**Comment by way2song** [comment]
Hello team! Any news?

**Comment by krenuser** [comment]
> Ugly, bad and generally non-recommended, but 100%-guaranteed workaround about Yandex.Browser: ![image](https://user-images.githubusercontent.com/103184392/195592261-c4ff5f0f-4b7e-43ea-bca9-6c8ba93515b5.png)

Still works using this patch)

**Comment by trufanov-nok** [comment]
Same problem on Linux.  
`yandex-browser-stable --user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36"`
didn't work...

**Comment by KevLehman** [comment]
Thanks for reporting, we don't officially support Yandex, so we can recommend you to raise the issue on them or use a compatible browser
