### ISSUE TITLE
migration v216 fails when migrating from 3.11.6 to 4.4.1

### ISSUE THREAD

**Issue by fuminori-ido-m** [RocketChat/Rocket.Chat#27015]
### Description:

migration v216 fails when migrating from 3.11.6 to 4.4.1

#### Comment

I guess [the migration](https://github.com/RocketChat/Rocket.Chat/blob/4.5.7/server/startup/migrations/v216.js) uses `Settings` module but it fails with rocketchat v4.x code.

My workaround is to upgrade to 3.18.7 (latest of 3.x) and then to 4.x.  Basically, [document](https://docs.rocket.chat/quick-start/upgrading-rocket.chat) only mentions about:

>  must not skip any major version

but 2 steps of upgrade are necessary in my case.  I hope some fix on this migration or adding a NOTE on upgrade-document.

### Steps to reproduce:

1. prepare rocketchat < ver.3.12
2. try to upgrade to 4.4.1

### Expected behavior:

migration completed and rocketchat runs

### Actual behavior:

migration fails with the following message:

> +----------------------------------------------------------------------+
> |                         ERROR! SERVER STOPPED                        |
> +----------------------------------------------------------------------+
> |                                                                      |
> |  Your database migration failed:                                     |
> |  Settings.insert is not a function                                   |
> 

### Server Setup Information:

- Version of Rocket.Chat Server: 3.11.6
- Operating System: Debian ( [docker image 3.11.6](https://hub.docker.com/layers/rocketchat/rocket.chat/3.11.6/images/sha256-da55825a02ed9e212405f7406beeb1c74c5dafe6966636aef82a7cd853bb2604?context=explore) )
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: ?
- NodeJS Version: v12.18.4
- MongoDB Version: 3.6.23

### Client Setup Information

- Desktop App or Browser Version: n/a
- Operating System: n/a

### Relevant logs:

> {"level":51,"time":"2022-10-04T07:05:39.484Z","pid":1,"hostname":"chatops-app-695779b959-qhzdm","name":"","name":"Migrations","msg":"Migrating from version 215 -> 254"}
> {"level":51,"time":"2022-10-04T07:05:39.485Z","pid":1,"hostname":"chatops-app-695779b959-qhzdm","name":"","name":"Migrations","msg":"Running up() on version 216"}
> +----------------------------------------------------------------------+
> |                         ERROR! SERVER STOPPED                        |
> +----------------------------------------------------------------------+
> |                                                                      |
> |  Your database migration failed:                                     |
> |  Settings.insert is not a function                                   |
> |                                                                      |
> |  Please make sure you are running the latest version and try again.  |
> |  If the problem persists, please contact support.                    |
> |                                                                      |
> |  This Rocket.Chat version: 4.4.1                                     |
> |  Database locked at version: 215                                     |
> |  Database target version: 254                                        |
> |                                                                      |
> |  Commit: 55598c2f757a286820553543f6abc176db5e440b                    |
> |  Date: Mon Feb 7 14:57:08 2022 -0300                                 |
> |  Branch: HEAD                                                        |
> |  Tag: 4.4.1                                                          |
> |                                                                      |
> +----------------------------------------------------------------------+
> {"level":50,"time":"2022-10-04T07:05:39.492Z","pid":1,"hostname":"chatops-app-695779b959-qhzdm","name":"","name":"Migrations","err":{"type":"TypeError","message":"Settings.insert is not a function","stack":"TypeError: Settings.insert is not a function\n
>     at server/startup/migrations/v216.js:20:21\n
>     at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40\n => awaited here:\n
>

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
