### ISSUE TITLE
Fibers native library missing linux-x64-59, node-gyp complains on graceful-fs.

### ISSUE THREAD

**Issue by monty241** [RocketChat/Rocket.Chat#9997]
### Description:

After upgrade from 0.59.3 to 0.62.1, RocketChat log shows the following error:

```
root@ws999:/opt/Rocket.Chat# nodejs main.js
## There is an issue with `node-fibers` ##
`/opt/Rocket.Chat/programs/server/node_modules/fibers/bin/linux-x64-59/fibers.node` is missing.

Try running this to fix the issue: /usr/bin/node /opt/Rocket.Chat/programs/server/node_modules/fibers/build
/opt/Rocket.Chat/programs/server/node_modules/fibers/fibers.js:20
                throw new Error('Missing binary. See message above.');
                ^

Error: Missing binary. See message above.
    at Object.<anonymous> (/opt/Rocket.Chat/programs/server/node_modules/fibers/fibers.js:20:9)
    at Module._compile (module.js:662:30)
    at Object.Module._extensions..js (module.js:673:10)
    at Module.load (module.js:575:32)
    at tryModuleLoad (module.js:515:12)
    at Function.Module._load (module.js:507:3)
    at Module.require (module.js:606:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/opt/Rocket.Chat/programs/server/boot.js:1:75)
    at Module._compile (module.js:662:30)
```

The native library in `linux-x64-59` folder of fibers is not present.

Running node-gyp to build it:

```
root@ws999:/opt/Rocket.Chat/programs/server/node_modules/fibers# node-gyp rebuild
module.js:559
    throw err;
    ^

Error: Cannot find module 'graceful-fs'
    at Function.Module._resolveFilename (module.js:557:15)
    at Function.Module._load (module.js:484:25)
    at Module.require (module.js:606:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/share/node-gyp/lib/node-gyp.js:12:10)
    at Module._compile (module.js:662:30)
    at Object.Module._extensions..js (module.js:673:10)
    at Module.load (module.js:575:32)
    at tryModuleLoad (module.js:515:12)
    at Function.Module._load (module.js:507:3)
```

Hwoever, graceful-fs is installed in both /opt/Rocket.Chat/programs/server/node_modules/graceful-fs and /usr/local/lib/node_modules.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.62.1
* Operating System: Ubuntu 14.04.5 LTS (3.13.0-74-generic #118-Ubuntu SMP Thu Dec 17 22:52:10 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux)
* Deployment Method(snap/docker/tar/etc): tar
* Number of Running Instances: 1
* DB Replicaset Oplog:  ?
* Node Version: v9.7.1
* NPM: 2.15.9ap
* mongoDB Version:  v3.0.15

### Steps to Reproduce:

`# cd /opt/Rocket.Chat`
`# nodejs main.js`

### Expected behavior:

RocketChat starts as with previous release.

**Comment by monty241** [comment]
Strace reveals:

```
stat("/usr/share/node-gyp/lib/node_modules", 0x7ffe507b61c0) = -1 ENOENT (No such file or directory)
stat("/usr/share/node-gyp/node_modules", 0x7ffe507b61c0) = -1 ENOENT (No such file or directory)
stat("/usr/share/node_modules", 0x7ffe507b61c0) = -1 ENOENT (No such file or directory)
stat("/usr/node_modules", 0x7ffe507b61c0) = -1 ENOENT (No such file or directory)
stat("/node_modules", 0x7ffe507b61c0)   = -1 ENOENT (No such file or directory)
stat("/root/.node_modules", 0x7ffe507b61c0) = -1 ENOENT (No such file or directory)
stat("/root/.node_libraries", 0x7ffe507b61c0) = -1 ENOENT (No such file or directory)
stat("/usr/lib/node", 0x7ffe507b61c0)   = -1 ENOENT (No such file or directory)
mmap(0x2e6b6c980000, 1048576, PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_NORESERVE, -1, 0) = 0x2e6b6c980000
munmap(0x2e6b6ca00000, 524288)          = 0
mmap(0x2e6b6c980000, 524288, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x2e6b6c980000
write(2, "module.js:559\n    throw err;\n   "..., 559module.js:559
```
When I've created node_modules in /usr/share/node-gyp and installed graceful-fs, the following error occurred on node-gyp execution:
```
Error: cannot find module 'nopt'
```
It seems that node-gyp does not look in /usr/local/lib/node_modules.

**Comment by monty241** [comment]
But running `node-gyp rebuild` did not create a new file. I had to run `nodejs build` from the folder /opt/Rocket.Chat/programs/server/node_modules/fibers.

After this the fibers error on missing native library was gone. Probably a bad solution, but for now it helps. Next time we will next to drop rocketchat server and create a new one from scratch.

**Comment by bennlich** [comment]
After upgrading to 0.62.2 from 0.61.0, I also saw:
```
Exception in callback of async function: Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /opt/Rocket.Chat/programs/server/npm/node_modules/sharp/build/Release/sharp.node)
```
The fix for me was to install gcc 4.9 as described [here](https://stackoverflow.com/a/37628537), and then manually specify the lib path in my rocket chat start script:
```
export ROOT_URL=blah
export MONGO_URL=blah
export LD_LIBRARY_PATH=/usr/lib/gcc/x86_64-linux-gnu/4.9.4
node main.js
```

**Comment by shionphan** [comment]
solved by this link: https://askubuntu.com/questions/466651/how-do-i-use-the-latest-gcc-on-ubuntu
