### ISSUE TITLE
admin - info page not showing anything

### ISSUE THREAD

**Issue by chojunki** [RocketChat/Rocket.Chat#15497]
### Steps to reproduce:

1.  upgrade your CentOS from 7.6 to 7.7
2.  upgrade mongodb from 3.6 to 4.0. then to 4.2
3.  delete Rocket.Chat 2.0 and install 2.1.0, start server.
4. login to admin page and click info menu, then no change shown. info page not shown.

### Expected behavior:

Info page shown when clicking info menu.

### Actual behavior:

info page not shown and previous page remains. no change.

### Server Setup Information:

- Version of Rocket.Chat Server: 2.1.0
- Operating System: CentOS 7.7
- Deployment Method:  Manual Install
- Number of Running Instances: 1
- DB Replicaset Oplog: enabled
- NodeJS Version: 8.15.1
- MongoDB Version: 4.2.0

### Relevant logs:

No special logs collected.

**Comment by reetp** [comment]
Check the supported engine versions.

https://github.com/RocketChat/Rocket.Chat/releases

 Engine versions

Node: 8.15.1

NPM: 6.9.0

MongoDB: 3.4, 3.6, 4.0


No mention of Mongo 4.2 so YMMV. 

What do your logs tell you?

**Comment by chojunki** [comment]
> Check the supported engine versions.
> 
> https://github.com/RocketChat/Rocket.Chat/releases
> 
> Engine versions
> 
> Node: 8.15.1
> 
> NPM: 6.9.0
> 
> MongoDB: 3.4, 3.6, 4.0
> 
> No mention of Mongo 4.2 so YMMV.
> 
> What do your logs tell you?

No specific logs. Nothing in Rocket.Chat logs. No info's and no warnings.

**Comment by Gummikavalier** [comment]
Info page works for us (Mongo 3.6) but the data on it stopped updating on it after upgrading to 2.0.0 or 2.1.0.

**Comment by reetp** [comment]
> > No mention of Mongo 4.2 so YMMV.
> > What do your logs tell you?
> 
> No specific logs. Nothing in Rocket.Chat logs. No info's and no warnings.

Did you revert to Mongo 4.0 and test?
I am not sure 4.2 is supported at the minute (as per the 'supported' engine versions)

**Comment by reetp** [comment]
> Info page works for us (Mongo 3.6) but the data on it stopped updating after upgrading to 2.0.0 or 2.1.0.

v2.0.0. or v2.1.0 ? Please be specific.

**Comment by Gummikavalier** [comment]
> > Info page works for us (Mongo 3.6) but the data on it stopped updating after upgrading to 2.0.0 or 2.1.0.
> 
> v2.0.0. or v2.1.0 ? Please be specific.

I cannot say for certain whether it happened already with 2.0.0, except that I usually check user amount stats on almost daily basis, and I don't remember seeing issues before 2.1.0 after which I noticed that logged in users does not match with actual amounts online. Then I also noticed that message counters didn't increase anymore.

**Comment by erkankyn1** [comment]
I have the same issue. How to fix this bug?

**Comment by corne-w** [comment]
Same issue here when performing an upgrade on my test environment from RocketChat 1.1.1 to 2.1.0. I get the following error in the browser console when trying to open the /admin/info page.

`
Uncaught (in promise) Error: Cannot find module '/client/components/admin/info/InformationPage.js'
`

I'm using the official docker container combined with MongoDB 4.0.1

**Comment by antkaz** [comment]
@corne-w I had the same problem. Does your host match the host in the settings?
In the settings I set the correct host and the problem was solved (Administration -> General -> Site URL)

**Comment by corne-w** [comment]
@antkaz Thank you, that seemed to have fixed the issue for me. The /admin/info page now works fine while using RocketChat 2.1.0 but only when using the exact url that was registered as the site url. For example:

Site URL: https://rocketchat.sub.example.org
FQDN: https://rocketchat.sub.example.org/admin/info <- Works.
Host: https://rocketchat/admin/info <- Doesn't work

Just to be sure that this bug didn't exist in the previous version (RC: 1.1.1) that I was using, I fired up the old test environment with incorrect host settings and it worked fine.

**Comment by Gummikavalier** [comment]
I did some double checking via statistics in the database, and ours seems to work too. Data is updating, although not so often I had assumed.

We had the correct URL to begin with, so our data-not-updating-issue was a brainfart on my behalf. Sorry for the confusion!

**Comment by erkankyn1** [comment]
> @antkaz Thank you, that seemed to have fixed the issue for me. The /admin/info page now works fine while using RocketChat 2.1.0 but only when using the exact url that was registered as the site url. For example:
> 
> Site URL: https://rocketchat.sub.example.org
> FQDN: https://rocketchat.sub.example.org/admin/info <- Works.
> Host: https://rocketchat/admin/info <- Doesn't work
> 
> Just to be sure that this bug didn't exist in the previous version (RC: 1.1.1) that I was using, I fired up the old test environment with incorrect host settings and it worked fine.

Thanks for helping. I will try this step on my server. I downgraded my server's version for this issue. I hope it works. I will turn back to you.

**Comment by antkaz** [comment]
This problem is related to the `dynamic-import` package. This package dynamically imports modules at runtime. The environment variable ROOT_URL is used as the hostname for loading the modules, but this variable is replaced by the value of Site_Url [here](https://github.com/RocketChat/Rocket.Chat/blob/develop/app/lib/lib/startup/settingsOnLoadSiteUrl.js#L19). If i remove this line, the information page will work. But I'm not sure if this is right

**Comment by chojunki** [comment]
How about checking if /admin/info works with rocketchat confirured to run in subdirectory like this:

http://xxx.yyy.com/xxchat/

This is my configuration and maybe a clue for this issue.

**Comment by antkaz** [comment]
The problem concerns not only the information page. If you try to open other pages in the administrator settings, you will get a similar error (`Cannot find module...`)

**Comment by erkankyn1** [comment]
> This problem is related to the `dynamic-import` package. This package dynamically imports modules at runtime. The environment variable ROOT_URL is used as the hostname for loading the modules, but this variable is replaced by the value of Site_Url [here](https://github.com/RocketChat/Rocket.Chat/blob/develop/app/lib/lib/startup/settingsOnLoadSiteUrl.js#L19). If i remove this line, the information page will work. But I'm not sure if this is right

Thanks for helping, this step works for mine RocketChat server.

**Comment by ggazzo** [comment]
closed by https://github.com/RocketChat/Rocket.Chat/pull/15598
