### ISSUE TITLE
502 error after update 4.0.1

### ISSUE THREAD

**Issue by web9ak** [RocketChat/Rocket.Chat#4400]
After upgrading from version 0.39.0 to 0.40.1, chat an error 502. OS - Red Hat 4.4.6-4
1. node -v -  v6.6.0.
2. sudo n install 4.5 - install : node-vinstall :  Error: invalid version install.
3. Error from logfile 
-------------
assert.js:93
  throw new assert.AssertionError({
        ^
AssertionError: "undefined" === "function"
    at wrapPathFunction (/root/Rocket.Chat/programs/server/mini-files.js:77:10)
    at Object.<anonymous> (/root/Rocket.Chat/programs/server/mini-files.js:108:$
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/root/Rocket.Chat/programs/server/boot.js:9:13)
    at Module._compile (module.js:456:26)
error: Forever detected script exited with code: 8
error: Script restart attempt #24

**Comment by engelgabriel** [comment]
node -v should be 4.5.0

**Comment by Flauschbaellchen** [comment]
Type `n 4.5` to change the version - the docs stating a wrong syntax.

**Comment by web9ak** [comment]
I set 4.5.0 ver.

Error from log 

Error: Cannot find module 'is-property'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/root/Rocket.Chat/programs/server/npm/node_modules/m$
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Module.Mp.load (/root/Rocket.Chat/programs/server/npm/node_modules/meteo$
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)

**Comment by engelgabriel** [comment]
did you do a `npm install` before running?

**Comment by engelgabriel** [comment]
See:
https://github.com/meteor/meteor/issues/7358
https://forums.meteor.com/t/cannot-find-module-is-property/26029/5

Please reopen if the problem persists
